export const jsonData =
{
    "p2pStatusResponseList": [
        {
            "id": 1,
            "cio": "CTO",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-05-30T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "Yes",
            "primaryAppId": "MQ4U",
            "primaryAppName": "MQ HOSTING",
            "sourceHostName": "CCPRM01A0021",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CCPRM01A0021",
            "sourceSerialNumber": "MXQ64105BX",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.178.82",
            "sourceRack": "301.04",
            "sourceRackUnit": "12",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "PLATMGMT-MWS-INTEGRATION",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "UAT",
            "sourceRam": "257325",
            "sourceCpu": "16.0",
            "targetHostName": "CCPRM01A0021",
            "targetEnvironment": "UAT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.178.82",
            "targetCluster": "DANDRWA53000-RD",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "102.23 MAPR - BD01SLSD9901",
            "targetRackUnit": "5",
            "migrationGroup": "Group 14"
        },
        {
            "id": 2,
            "cio": "CTO",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-05-30T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "Yes",
            "primaryAppId": "MQ4U",
            "primaryAppName": "MQ HOSTING",
            "sourceHostName": "CCPRM01A0023",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CCPRM01A0023",
            "sourceSerialNumber": "MXQ64105BT",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.178.108",
            "sourceRack": "301.04",
            "sourceRackUnit": "8",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "PLATMGMT-MWS-INTEGRATION",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "UAT",
            "sourceRam": "257325",
            "sourceCpu": "16.0",
            "targetHostName": "CCPRM01A0023",
            "targetEnvironment": "UAT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.178.108",
            "targetCluster": "testCluster2",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "100.20 MAPR - BD03SLSD0301",
            "targetRackUnit": "5",
            "migrationGroup": "Group 14"
        },
        {
            "id": 3,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Traditional-Compute",
            "sanAttached": "No",
            "primaryAppId": "PSCOH",
            "primaryAppName": "WFS COHERENCE CACHE",
            "sourceHostName": "CDPRA00A0039",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CDPRA00A0039",
            "sourceSerialNumber": "MXQ642081P",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.177.173",
            "sourceRack": "304.06 DCAM NP",
            "sourceRackUnit": "14",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "WHLSWFSCACHESERVICES",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "DEVELOPMENT",
            "sourceRam": "515331",
            "sourceCpu": "36.0",
            "targetHostName": "CDPRA00A0039",
            "targetEnvironment": "DEVELOPMENT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.177.173",
            "targetCluster": "DANPXW690001-XU--4431681",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "101.24 MAPR - BD01SLSD9401",
            "targetRackUnit": "5",
            "migrationGroup": "Group 1"
        },
        {
            "id": 4,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Traditional-Compute",
            "sanAttached": "No",
            "primaryAppId": "PSCOH",
            "primaryAppName": "WFS COHERENCE CACHE",
            "sourceHostName": "CDPRA00A0044",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CDPRA00A0044",
            "sourceSerialNumber": "MXQ642082N",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.177.178",
            "sourceRack": "304.06 DCAM NP",
            "sourceRackUnit": "4",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "WHLSWFSCACHESERVICES",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "DEVELOPMENT",
            "sourceRam": "515331",
            "sourceCpu": "36.0",
            "targetHostName": "CDPRA00A0044",
            "targetEnvironment": "DEVELOPMENT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.177.178",
            "targetCluster": "DANPXW690001-XU--4431681",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "101.24 MAPR - BD01SLSD9401",
            "targetRackUnit": "5",
            "migrationGroup": "Group 1"
        },
        {
            "id": 5,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Traditional-Compute",
            "sanAttached": "No",
            "primaryAppId": "PSCOH",
            "primaryAppName": "WFS COHERENCE CACHE",
            "sourceHostName": "CDPRA00A0053",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CDPRA00A0053",
            "sourceSerialNumber": "MXQ642081R",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.177.187",
            "sourceRack": "304.05 DCAM NP",
            "sourceRackUnit": "6",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "WHLSWFSCACHESERVICES",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "DEVELOPMENT",
            "sourceRam": "515331",
            "sourceCpu": "36.0",
            "targetHostName": "CDPRA00A0053",
            "targetEnvironment": "DEVELOPMENT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.177.187",
            "targetCluster": "DANPXW690001-XU--4431681",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "101.24 MAPR - BD01SLSD9401",
            "targetRackUnit": "5",
            "migrationGroup": "Group 1"
        },
        {
            "id": 6,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Traditional-Compute",
            "sanAttached": "No",
            "primaryAppId": "PSCOH",
            "primaryAppName": "WFS COHERENCE CACHE",
            "sourceHostName": "CDPRA00A0054",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CDPRA00A0054",
            "sourceSerialNumber": "MXQ642081Y",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.177.188",
            "sourceRack": "304.05 DCAM NP",
            "sourceRackUnit": "4",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "WHLSWFSCACHESERVICES",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "DEVELOPMENT",
            "sourceRam": "515331",
            "sourceCpu": "36.0",
            "targetHostName": "CDPRA00A0054",
            "targetEnvironment": "DEVELOPMENT",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.177.188",
            "targetCluster": "DANPXW690001-XU--4431681",
            "targetNetworkZone": "PROD-CDE",
            "targetRack": "101.24 MAPR - BD01SLSD9401",
            "targetRackUnit": "5",
            "migrationGroup": "Group 1"
        },
        {
            "id": 7,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Traditional-Compute",
            "sanAttached": "No",
            "primaryAppId": "PSCOH",
            "primaryAppName": "WFS COHERENCE CACHE",
            "sourceHostName": "CSPRA00A0027",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CSPRA00A0027",
            "sourceSerialNumber": "MXQ6420820",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.177.167",
            "sourceRack": "304.07 DCAM 15",
            "sourceRackUnit": "6",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "WHLSWFSCACHESERVICES",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "SIT/IST",
            "sourceRam": "515331",
            "sourceCpu": "36.0",
            "targetHostName": "CSPRA00A0027",
            "targetEnvironment": "SIT/IST",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.177.167",
            "migrationGroup": "Group 17"
        },
        {
            "id": 8,
            "cio": "EFT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-03-31T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "Yes",
            "primaryAppId": "1GSM",
            "primaryAppName": "GLOBAL SANCTIONS MANAGEMENT OPERATIONS SYSTEM",
            "sourceHostName": "CUP1GSM00A003",
            "sourceModelName": "HPE PROLIANT DL380 G10 SERVER",
            "sourceCiType": "CUP1GSM00A003",
            "sourceSerialNumber": "2M204804HJ",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "868703-B21",
            "sourceIp": "10.144.145.230",
            "sourceRack": "111.02 DCAM",
            "sourceRackUnit": "28",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "CUSTOMERDUEDILIGENCE",
            "sourceTscName": "HPE PROLIANT DL380 G10 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "UAT",
            "sourceRam": "262144",
            "sourceCpu": "16.0",
            "targetHostName": "CUP1GSM00A003",
            "targetEnvironment": "UAT",
            "targetDatacenter": "Silas",
            "targetIp": "10.144.145.230",
            "migrationGroup": "Group 2"
        },
        {
            "id": 9,
            "cio": "CCIBT",
            "neighborhood": "non-production",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2025-05-31T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "Yes",
            "primaryAppId": "1MCR",
            "primaryAppName": "MARKET RISK SYSTEM",
            "sourceHostName": "CUPWD00A0068",
            "sourceModelName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceCiType": "CUPWD00A0068",
            "sourceSerialNumber": "MXQ7160JGN",
            "sourceManufacturer": "HEWLETT-PACKARD",
            "sourceModelNumber": "719064-B21",
            "sourceIp": "162.111.224.221",
            "sourceRack": "301.20 (Q1 2017)",
            "sourceRackUnit": "2",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "MARKETRISKDEV",
            "sourceTscName": "HPE PROLIANT DL380 G9 SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "SIT/IST",
            "sourceRam": "524288",
            "sourceCpu": "36.0",
            "targetHostName": "CUPWD00A0068",
            "targetEnvironment": "SIT/IST",
            "targetDatacenter": "Silas",
            "targetIp": "162.111.224.221",
            "migrationGroup": "Group 13"
        },
        {
            "id": 10,
            "cio": "CTO",
            "neighborhood": "Technology Enablement Services",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-05-30T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "No",
            "primaryAppId": "DANHP",
            "primaryAppName": "DAN HIGH PERFORMANCE DATABASE SOLUTION FOR ORACLE",
            "sourceHostName": "DANPXW6900CE08",
            "sourceModelName": "ORACLE SERVER",
            "sourceCiType": "DANPXW6900CE08",
            "sourceSerialNumber": "1615NM70VX",
            "sourceManufacturer": "ORACLE",
            "sourceModelNumber": "X6-2",
            "sourceRack": "139.69 EXADATA",
            "sourceRackUnit": "27",
            "sanFabric": "San_fabric",
            "sourceManagedGroup": "DBS-EXADATA",
            "sourceTscName": "ORACLE SERVER",
            "sourceDatacenter": "WEC",
            "sourceEnvironment": "PRODUCTION",
            "targetHostName": "DANPXW6900CE08",
            "targetEnvironment": "PRODUCTION",
            "targetDatacenter": "Silas",
            "migrationGroup": "Out of Scope"
        },
        {
            "id": 11,
            "cio": "CTOD",
            "neighborhood": "Technology Enablement Services",
            "migrationMethod": "Lift & Shift",
            "targetDate": "2026-05-30T00:00:00.000+00:00",
            "targetPlatform": "Private-IaaS",
            "sanAttached": "No",
            "primaryAppId": "DANHP",
            "primaryAppName": "DAN HIGH PERFORMANCE DATABASE SOLUTION FOR ORACLE",
            "sourceHostName": "DANPXW6900CE12",
            "sourceModelName": "ORACLE SERVER",
            "sourceCiType": "DANPXW6900CE12",
            "sourceSerialNumber": "1615NM70XF",
            "sourceManufacturer": "ORACLE",
            "sourceModelNumber": "X6-2",
            "sourceRack": "139.69 EXADATA",
            "sourceRackUnit": "35",
            "sanFabric": "San_fabric",
        }
	],
    "totalRecords": 20
}